name=fastlib
version=1.0.0
author=Mrinmoy <info@mrinmoy.indevs.in>
maintainer=Mrinmoy <info@mrinmoy.indevs.in>
sentence=One Arduino, One Library.
paragraph=CC1101
category=
url=https://github.com/mrnmoy/fastlib
architectures=*
includes=fastlib.h
